Vagrant.configure("2") do |config|
    config.vm.define "acetinS" do |server|
      server.vm.network :private_network, ip: "192.168.56.110", name:"iot"
      server.vm.hostname = "acetinS"
      server.vm.provider "docker" do |docker|
        docker.privileged = true
        docker.build_dir = "."
        docker.dockerfile = "confs/Dockerfile"
        docker.name = "acetinS"
        docker.has_ssh = true
        docker.remains_running = true
        # docker.create_args = ["--cpus=1", "--memory=1024m"]
      end
      server.vm.provision "shell", path: "./scripts/initilaize.sh"
    end
end
  