#vagrant plugin install vagrant-vbguest //synced_folder mount ayarlamak için
# vagrant plugin install virtualbox_WSL2 wsl2 ile ssh hatası alındığı zaman ki çözüm

Vagrant.configure("2") do |config|
    config.vm.define "acetinS" do |server|
      server.vm.network :private_network, ip: "192.168.56.110", name:"iot"
      server.vm.hostname = "acetinS"
      server.vm.provider "docker" do |docker|
        docker.privileged = true
        docker.build_dir = "."
        docker.dockerfile = "confs/Dockerfile"
        docker.name = "acetinS"
        docker.has_ssh = true
        docker.remains_running = true
        docker.create_args = ["--cpus=1", "--memory=1024m"]
      end
      server.vm.provision "shell", path:"./scripts/initilaize.sh"
    end
    config.vm.define "acetinSW" do |serverWorker|
      serverWorker.vm.hostname = "acetinSW"
      serverWorker.vm.network :private_network, ip: "192.168.56.111", name:"iot"
      serverWorker.vm.provider "docker" do |docker|
        docker.privileged = true
        docker.build_dir = "."
        docker.dockerfile = "confs/Dockerfile"
        docker.name = "acetinSW"
        docker.has_ssh = true
        docker.remains_running = true
        docker.create_args = ["--cpus=1", "--memory=1024m"]
      end
      serverWorker.vm.provision "shell", path:"./scripts/initilaize.sh"
    end
  end
 
### docker subnet ayarlama 
# cat /etc/docker/daemon.json 
# {
#     "bip": "192.168.56.1/16"
# }
#echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
# docker inspect <container_id_or_name> --format='{{.HostConfig.NanoCpus}}'
# docker inspect <container_id_or_name> --format='{{.HostConfig.Memory}}' | awk '{print $1/1024/1024 " MB"}'

